#ifndef GLW_CONFIG_H
#define GLW_CONFIG_H

#ifndef GLW_ASSERT
#	define GLW_ASSERT assert
#endif

#ifndef GLW_IMPLEMENT_CUSTOM_UNIFORMS
#	define GLW_IMPLEMENT_CUSTOM_UNIFORMS
#endif

#ifndef GLW_PRINT_LOG_TO_STDERR
#	define GLW_PRINT_LOG_TO_STDERR 1
#endif

#ifndef GLW_ASSERT_UNIFORM_LOCATION
#	define GLW_ASSERT_UNIFORM_LOCATION 0
#endif

#endif // GLW_CONFIG_H
